apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: slo-reporter-buildconfig
  annotations:
    description: This is Thoth Core - SLO Reporter Job BuildConfig
    openshift.io/display-name: "Thoth: SLO Reporter Job BuildConfig"
    version: 0.1.0
    tags: poc,thoth,ai-stacks,slo-reporter
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to deploy Thoth
      SLO Reporter as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
    thoth-station.ninja/template-version: 0.1.0
  labels:
    template: slo-reporter-buildconfig
    app: thoth
    component: slo-reporter

objects:
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: slo-reporter
      annotations:
        thoth-station.ninja/template-version: 0.1.0
      labels:
        app: thoth
        component: slo-reporter
    spec:
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 1000m
          memory: 1Gi
      output:
        to:
          kind: ImageStreamTag
          name: "slo-reporter:${IMAGE_STREAM_TAG}"
      source:
        type: Git
        git:
          uri: ${GITHUB_URL}
          ref: ${GITHUB_REF}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: s2i-thoth-ubi8-py36:latest
          env:
            - name: ENABLE_PIPENV
              value: '1'
            - name: UPGRADE_PIP_TO_LATEST
              value: ''
            - name: "THOTH_DRY_RUN"
              value: "1"
            - name: "THOTH_ADVISE"
              value: ${THOTH_ADVISE}
            - name: "THOTH_PROVENANCE_CHECK"
              value: ${THOTH_PROVENANCE_CHECK}
            - name: THOTH_ERROR_FALLBACK
              value: "0"
            - name: DISABLE_SETUP_PY_PROCESSING
              value: "1"
            - name: "THAMOS_VERBOSE"
              value: "1"
            - name: "THAMOS_DEBUG"
              value: "0"
            - name: "THAMOS_CONFIG_TEMPLATE"
              value: ".thoth.yaml"
            - name: "THAMOS_CONFIG_EXPAND_ENV"
              value: "1"
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChange: {}
        - type: "Generic"
          generic:
            secretReference:
              name: generic-webhook-secret

parameters:
  - description: Name of the github repository for Thoth's SLO Reporter
    displayName: Git Repository
    required: true
    name: GITHUB_URL
    value: 'https://github.com/thoth-station/slo-reporter'

  - description: Git reference to be used for Thoth's SLO Reporter
    displayName: Git Reference
    required: true
    name: GITHUB_REF
    value: 'master'

  - description: >
      Tag of the output ImageStream the resulting container image should go to
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: 'latest'

  - description: Thamos Advise setup tag value
    displayName: THOTH_ADVISE
    required: true
    name: THOTH_ADVISE
    value: "0"

  - description: Thamos Provenance Check setup tag flag
    displayName: THOTH_PROVENANCE_CHECK
    required: false
    name: THOTH_PROVENANCE_CHECK
    value: "0"
